### ISSUE TITLE
How to finish model level transfer in this code

### ISSUE THREAD

**Issue by neverneverendup** [abhipec/FgEC#1]
Dear Author,
I want to do the transfer with this new tensorflow 1.10 code FgEC.How can I do?Thanks~

**Comment by abhipec** [comment]
Hi,
It is currently not available on this repo. I had done some related experiments offline. Will update the repo to include transfer learning code may be in couple of days.

**Comment by neverneverendup** [comment]
OK!Thank you very much~Wait for your work 😄

**Comment by abhipec** [comment]
@neverneverendup Code base updated to include model level transfer learning code. Please have a look at : FgEC/src/scripts/TL_OntoNotes_on_BBN.bash
