### ISSUE TITLE
what's is the meaning of the printout

### ISSUE THREAD

**Issue by ooCher** [abhipec/FgEC#2]
Excuse me. I am so sorry to bother you. I run your code in my machine. And I run this code for about 3 hours, and I just can't understand what's is the meaning of the printout. And I want to know if there were something wrong with it? And how I get the results of this code?  I am looking forward to your reply.

2019-05-20 09:13:30.367340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2019-05-20 09:13:30.367882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-20 09:13:30.367898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 2 3 4 5 6 7
2019-05-20 09:13:30.367907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N Y Y Y N N N N
2019-05-20 09:13:30.369894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 10417 MB memory) -> physical GPU (device: 7, name: GeForce GTX 1080 Ti, pci bus id: 0000:89:00.0, compute capability: 6.1)
embeddings/char_embeddings:0
embeddings/label_embedding:0
rnn-mentions/lstm_cell/kernel:0
rnn-mentions/lstm_cell/bias:0
lc-bidirectional/fw/lstm_cell/kernel:0
lc-bidirectional/fw/lstm_cell/bias:0
lc-bidirectional/bw/lstm_cell/kernel:0
lc-bidirectional/bw/lstm_cell/bias:0
rc-bidirectional/fw/lstm_cell/kernel:0
rc-bidirectional/fw/lstm_cell/bias:0
rc-bidirectional/bw/lstm_cell/kernel:0
rc-bidirectional/bw/lstm_cell/bias:0

**Comment by abhipec** [comment]
Hi,
Can you be more specific? For example, which file you ran?

**Comment by ooCher** [comment]
I run the scripts/ontonotes.bash, and I don't know how to get the results that show on your paper. I means that I don't know how to get the Acc., Ma-F1 and Mi-F1 scores. And I want to know how many GPUs dose it needs. It took up all the GPUs when I ran yesterday, but actually only used one. But I did not finish running, only ran to run_5.

**Comment by abhipec** [comment]
Ok, Thanks for the info. 

The sricpt runs 5 model training sessions. 

Each session will be saved in the checkpoint directory with a suffix _1, _2, etc. '

The results of each session will be stored in a .txt file in these directories within a sub_directory named after the evaluation file name. Either one can manually go through these .txt files or report the best result automatically using the following script: 
```
python scripts/fnet_report_result_with_sd.py ckpt_directory_path/

```

I hope this helps.

**Comment by ooCher** [comment]
Thanks a lot. So this code just needs 1 GPU or more? And what is the relationship between these five sessions? Do I need run all to get the best result or just some of them. I am looking forward to your reply.

**Comment by abhipec** [comment]
It only requires one GPU. By defaut Tensorflow block every available GPU, you need to modify this code a little in order to change this behavior. Each session in a independent training session, wherein model weights are initialized randomly. This setting we followed for reporting result in the paper. However, you can train only one session if you wish to, just change the for loop variable.

**Comment by ooCher** [comment]
Thanks a lot. I'm glad you have answered my questions. And wish you a good day.

**Comment by abhipec** [comment]
You're welcome. I am closing this issue. If you have any further issues, feel free to open the issue. :)
